name: royal_marble
description: An app that would track the live location of workers.

version: 8.0.0

environment:
  sdk: ">=2.19.0<3.1.5"


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  firebase_storage: ^11.5.0
  cloud_firestore: ^4.13.0
  cloud_functions: ^4.5.4
  firebase_messaging: ^14.7.4
  firebase_database: ^10.3.4
  google_maps_flutter: ^2.5.0
  #device_info_plus: ^9.0.2
  sentry_flutter: ^7.12.0
  provider: ^6.1.1
  country_picker: ^2.0.20
  email_validator: ^2.0.17
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.0
  dio: ^5.3.3
  flutter_polyline_points: ^2.0.0
  url_launcher: ^6.1.14
  geolocator: ^9.0.2
  permission_handler: ^11.0.1
  flutter_typeahead: ^4.8.0
  geocoding: ^2.0.5
  image: ^4.1.3
  image_picker: ^1.0.4
  location: ^5.0.3
  flutter_background: ^1.2.0
  flutter_speed_dial: ^7.0.0
  shared_preferences: ^2.2.2
  flutter_background_geolocation: ^4.13.4
  background_geolocation_firebase: ^1.0.1
  latlong2: ^0.9.0
  flutter_map: ^6.0.1
  http: ^1.0.0
  intl: ^0.18.1
  syncfusion_flutter_datepicker: ^20.3.57
  uri_to_file: ^0.2.0
  pdf: ^3.10.4
  printing: ^5.11.1
  intl_phone_number_input: ^0.7.3+1
  timer_builder: ^2.0.0
  animated_text_kit: ^4.2.2
  path_provider: ^2.1.1
  open_filex: ^4.3.4
  syncfusion_flutter_xlsio: ^20.4.42-beta
  connectivity_plus: ^4.0.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/