name: royal_marble
description: An app that would track the live location of workers.

version: 4.0.0

environment:
  sdk: ">=2.19.0<3.1.5"


dependencies:
  flutter:
    sdk: flutter
  firebase_core: 1.24.0
  firebase_auth: 3.4.0
  firebase_storage: 10.3.4
  cloud_firestore: 3.5.0
  cloud_functions: 3.3.1
  firebase_messaging: 13.0.4
  firebase_database: 9.1.6
  google_maps_flutter: ^2.2.1
  device_info_plus: 8.1.0
  sentry_flutter: ^7.12.0
  provider: ^5.0.0
  country_picker: ^2.0.10
  email_validator: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  dio: ^4.0.5
  flutter_polyline_points: ^1.0.0
  url_launcher: ^6.1.1
  geolocator: ^9.0.2
  permission_handler: ^10.0.0
  flutter_typeahead: ^3.2.5
  geocoding: ^2.0.4
  image: ^3.1.1
  image_picker: ^0.8.6
  location: ^4.4.0
  flutter_background: ^1.1.0
  flutter_speed_dial: ^6.0.0
  shared_preferences: ^2.0.15
  flutter_background_geolocation: ^4.8.3
  background_geolocation_firebase: ^1.0.0
  latlong2: ^0.8.1
  flutter_map: ^3.0.0
  http: ^0.13.5
  intl: ^0.17.0
  syncfusion_flutter_datepicker: ^20.3.57
  uri_to_file: ^0.2.0
  pdf: ^3.8.4
  printing: ^5.9.3
  #flutter_cache_manager: ^3.3.0
  intl_phone_number_input: ^0.7.1
  timer_builder: ^2.0.0
  animated_text_kit: ^4.2.2
  path_provider: ^2.0.11
  open_filex: ^4.3.2
  syncfusion_flutter_xlsio: ^20.4.42-beta
  connectivity_plus: ^3.0.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/